### ISSUE TITLE
Move all enums into includes.h directly

### ISSUE THREAD

**Issue by TyrenDe** [VKoskiv/c-ray#15]
enums don't have any code, just put them somewhere they can be used globally.  Directly in includes.h or a separate .H file (one for each file, or one with all).

**Comment by VKoskiv** [comment]
I do want to keep the enums associated with the code that uses them. For instance, it makes sense for the `transformType` enum to be located in `transforms.h` since the functions that use that enum are also defined there.
Including the header also includes the enum as part of it, with the way I've structured the project now.
