### ISSUE TITLE
several missing obj and "unknown command" in "scene.json"

### ISSUE THREAD

**Issue by novelistparty** [VKoskiv/c-ray#36]
```
Loading OBJ input/teht1.obj
Error reading file: input/teht1.obj
OBJ teht1.obj file not found!
Failed to find OBJ named teht1.obj
```

```
Loading OBJ input/teapot_white.obj
Error reading file: input/teapot_white.obj
OBJ teapot_white.obj file not found!
Failed to find OBJ named teapot_white.obj
```

Lots of these

```
Unknown command 'Ke' in material file input/newScene.mtl at line 49:
	Ke
```

**Comment by VKoskiv** [comment]
Thanks for reporting!

These are to be expected. I've neglected to include all the OBJ models I'm using for my testing, so it just complains they can't be found.

It should work just fine regardless, you just won't see those objects being rendered.
I'll soon implement a better way of loading OBJs with custom material definitions, so we don't need to have several identical OBJ models taking up disk space.

The unknown command errors are due to C-ray not supporting all the PBR shader parameters yet, so it just doesn't recognise those yet. Another thing for the TODO!

**Comment by VKoskiv** [comment]
Also I just noticed it literally says the same thing 3 times in a row. That's funny!:

>Error reading file: input/teht1.obj
OBJ teht1.obj file not found!
Failed to find OBJ named teht1.obj
